// Theme configuration list
import { getHtmlColorScheme } from './html-tokens.js';
import { archetype, withAlpha } from './roles.js';
import { additionalThemes } from './theme-config-batch2.js';
import { finalThemes } from './theme-config-final.js';

// Complete theme definitions - migrated from manual to generated
export const themes = [
  {
    id: 'xela-black',
    name: 'XELA Black',
    type: 'dark',
    roles: archetype('black'),
    tokens(c){
      return {
        comment: '#8E93A6',
        keyword: '#FFD166',
        function: '#00F5A0',
        variable: '#EADCB2',
        string: '#22C55E',
        number: '#FFD166',
        constant: '#F2C97D',
        storage: '#FF3CAC',
        type: '#D8C8FF',
        punctuation: c.textPrimary,
        invalid: '#FF3366',
        code: c.textPrimary,
        heading: c.accentPrimary,
        h1: c.accentWarn,
        h2: '#F5F2E8',
        h3: '#FF8BDA',
        h4: c.accentPrimaryAlt,
        h5: c.accentSuccess,
        h6: c.textMuted,
        textPrimary: c.textPrimary
      };
    },
    htmlScheme: getHtmlColorScheme('black','dark')
  },
  {
    id: 'xela-matrix-rain',
    name: 'XELA Matrix Rain — Hyperphosphor Cascade',
    type: 'dark',
    roles: {
      surface0: '#000A06',
      surface1: '#000D09',
      surface2: '#072E1F',
      surface3: '#0B3A29',
      panel: '#000D09',
      overlay: '#000A06CC',
      backdrop: '#00000088',
      border: '#072E1F',
      focus: withAlpha('#00FF87',0.27),
      textPrimary: '#B9FDE4',
      textSecondary: '#A4F6D6',
      textMuted: '#6DEAB8',
      textInverted: '#003321',
      accentPrimary: '#00FF87',
      accentPrimaryAlt: '#72FFD4',
      accentInfo: '#4DFFAA',
      accentWarn: '#FFE66D',
      accentError: '#FF4D5E',
      accentSuccess: '#00FF88',
      accentSelection: withAlpha('#00FF87',0.25),
      accentLink: '#72FFD4'
    },
    tokens(c){
      return {
        comment: '#5A9C7E',
        keyword: '#00FF87',
        function: '#72FFD4',
        variable: '#B9FDE4',
        string: '#00FF88',
        number: '#72FFD4',
        constant: '#A4F6D6',
        storage: '#00FF87',
        type: '#4DFFAA',
        punctuation: c.textPrimary,
        invalid: '#FF4D5E',
        code: c.textPrimary,
        heading: c.accentPrimary,
        h1: '#00FF87',
        h2: '#72FFD4',
        h3: '#4DFFAA',
        h4: '#B9FDE4',
        h5: '#A4F6D6',
        h6: c.textMuted,
        textPrimary: c.textPrimary
      };
    },
    htmlScheme: getHtmlColorScheme('matrix','dark')
  },
  {
    id: 'xela-arctic',
    name: 'XELA Arctic — Crystal Light',
    type: 'light',
    roles: {
      surface0: '#F8FAFB',
      surface1: '#F3F6F8',
      surface2: '#EDF3F7',
      surface3: '#E8F1F7',
      panel: '#FFFFFF',
      overlay: '#FFFFFFCC',
      backdrop: '#FFFFFF88',
      border: '#E5EDF2',
      focus: withAlpha('#2980B9',0.67),
      textPrimary: '#2C3E50',
      textSecondary: '#34495E',
      textMuted: '#7F8C8D',
      textInverted: '#FFFFFF',
      accentPrimary: '#2980B9',
      accentPrimaryAlt: '#3498DB',
      accentInfo: '#16A085',
      accentWarn: '#F39C12',
      accentError: '#E74C3C',
      accentSuccess: '#27AE60',
      accentSelection: withAlpha('#2980B9',0.2),
      accentLink: '#2980B9'
    },
    tokens(c){
      return {
        comment: '#95A5A6',
        keyword: '#8E44AD',
        function: '#2980B9',
        variable: '#2C3E50',
        string: '#27AE60',
        number: '#E67E22',
        constant: '#9B59B6',
        storage: '#8E44AD',
        type: '#3498DB',
        punctuation: c.textPrimary,
        invalid: '#E74C3C',
        code: c.textPrimary,
        heading: c.accentPrimary,
        h1: '#2C3E50',
        h2: '#2980B9',
        h3: '#8E44AD',
        h4: '#16A085',
        h5: '#27AE60',
        h6: c.textMuted,
        textPrimary: c.textPrimary
      };
    },
    htmlScheme: getHtmlColorScheme('arctic','light')
  },
  {
    id: 'xela-night-vision',
    name: 'XELA Night Vision',
    type: 'dark',
    roles: {
      surface0: '#0B0F0A',
      surface1: '#0E130E',
      surface2: '#121812',
      surface3: '#162016',
      panel: '#0B0F0A',
      overlay: '#0B0F0ACC',
      backdrop: '#00000088',
      border: '#0E130E',
      focus: withAlpha('#6BFF3E',0.67),
      textPrimary: '#E4FFE4',
      textSecondary: '#D9FAD9',
      textMuted: '#B5CBB5',
      textInverted: '#061106',
      accentPrimary: '#6BFF3E',
      accentPrimaryAlt: '#A8FF74',
      accentInfo: '#6BFF3E',
      accentWarn: '#FFB224',
      accentError: '#FF5A87',
      accentSuccess: '#6BFF3E',
      accentSelection: withAlpha('#6BFF3E',0.13),
      accentLink: '#A8FF74'
    },
    tokens(c){
      return {
        comment: '#9DB39D',
        keyword: '#6BFF3E',
        function: '#A8FF74',
        variable: '#E4FFE4',
        string: '#6BFF3E',
        number: '#A8FF74',
        constant: '#D9FAD9',
        storage: '#6BFF3E',
        type: '#A8FF74',
        punctuation: c.textPrimary,
        invalid: '#FF5A87',
        code: c.textPrimary,
        heading: c.accentPrimary,
        h1: '#6BFF3E',
        h2: '#A8FF74',
        h3: '#D9FAD9',
        h4: '#B5CBB5',
        h5: '#9DB39D',
        h6: c.textMuted,
        textPrimary: c.textPrimary
      };
    },
    htmlScheme: getHtmlColorScheme('night-vision','dark')
  },
  {
    id: 'xela-vapor',
    name: 'XELA Vapor — Neon Retrowave',
    type: 'dark',
    roles: {
      surface0: '#1A0033',
      surface1: '#110026',
      surface2: '#2B0055',
      surface3: '#33003A',
      panel: '#110026',
      overlay: '#1A0033CC',
      backdrop: '#00000088',
      border: '#2B0055',
      focus: withAlpha('#FF00FF',0.67),
      textPrimary: '#EAD7FF',
      textSecondary: '#F7E9FF',
      textMuted: '#C9B1E6',
      textInverted: '#001A1A',
      accentPrimary: '#FF00FF',
      accentPrimaryAlt: '#00FFFF',
      accentInfo: '#00FFFF',
      accentWarn: '#FFB86C',
      accentError: '#FF5555',
      accentSuccess: '#50FA7B',
      accentSelection: withAlpha('#FF00FF',0.2),
      accentLink: '#00FFFF'
    },
    tokens(c){
      return {
        comment: '#BDA6DB',
        keyword: '#FF00FF',
        function: '#00FFFF',
        variable: '#EAD7FF',
        string: '#50FA7B',
        number: '#FFB86C',
        constant: '#BD93F9',
        storage: '#FF79C6',
        type: '#8BE9FD',
        punctuation: c.textPrimary,
        invalid: '#FF5555',
        code: c.textPrimary,
        heading: c.accentPrimary,
        h1: '#FF00FF',
        h2: '#00FFFF',
        h3: '#BD93F9',
        h4: '#FFB86C',
        h5: '#50FA7B',
        h6: c.textMuted,
        textPrimary: c.textPrimary
      };
    },
    htmlScheme: getHtmlColorScheme('vapor','dark')
  },
  {
    id: 'xela-phosphor-green',
    name: 'XELA Phosphor Green — Monochrome CRT',
    type: 'dark',
    roles: {
      surface0: '#000000',
      surface1: '#00110A',
      surface2: '#0D0D0D',
      surface3: '#0A3322',
      panel: '#00110A',
      overlay: '#000000CC',
      backdrop: '#00000088',
      border: '#0F0F0F',
      focus: withAlpha('#00FF7F',0.67),
      textPrimary: '#CCFFDD',
      textSecondary: '#B8FFCE',
      textMuted: '#88AA99',
      textInverted: '#00110A',
      accentPrimary: '#00FF7F',
      accentPrimaryAlt: '#33FF99',
      accentInfo: '#00FF7F',
      accentWarn: '#88AA99',
      accentError: '#AA8888',
      accentSuccess: '#00FF7F',
      accentSelection: withAlpha('#00FF7F',0.13),
      accentLink: '#33FF99'
    },
    tokens(c){
      return {
        comment: '#88AA99',
        keyword: '#00FF7F',
        function: '#33FF99',
        variable: '#CCFFDD',
        string: '#00FF7F',
        number: '#33FF99',
        constant: '#B8FFCE',
        storage: '#00FF7F',
        type: '#33FF99',
        punctuation: c.textPrimary,
        invalid: '#AA8888',
        code: c.textPrimary,
        heading: c.accentPrimary,
        h1: '#00FF7F',
        h2: '#33FF99',
        h3: '#CCFFDD',
        h4: '#B8FFCE',
        h5: '#88AA99',
        h6: c.textMuted,
        textPrimary: c.textPrimary
      };
    },
    htmlScheme: getHtmlColorScheme('phosphor','dark')
  },
  {
    id: 'xela-dark',
    name: 'XELA Dark — Balanced Dark',
    type: 'dark',
    roles: {
      surface0: '#0F0F0F',
      surface1: '#1A1A1A',
      surface2: '#242424',
      surface3: '#2E2E2E',
      panel: '#1A1A1A',
      overlay: '#0F0F0FCC',
      backdrop: '#00000088',
      border: '#333333',
      focus: withAlpha('#00A8FF',0.67),
      textPrimary: '#F0F0F0',
      textSecondary: '#D0D0D0',
      textMuted: '#A0A0A0',
      textInverted: '#0F0F0F',
      accentPrimary: '#00A8FF',
      accentPrimaryAlt: '#33B8FF',
      accentInfo: '#00A8FF',
      accentWarn: '#FFB347',
      accentError: '#FF6B6B',
      accentSuccess: '#4ECDC4',
      accentSelection: withAlpha('#00A8FF',0.2),
      accentLink: '#33B8FF'
    },
    tokens(c){
      return {
        comment: '#888888',
        keyword: '#C586C0',
        function: '#DCDCAA',
        variable: '#9CDCFE',
        string: '#CE9178',
        number: '#B5CEA8',
        constant: '#569CD6',
        storage: '#C586C0',
        type: '#4EC9B0',
        punctuation: c.textPrimary,
        invalid: '#F44747',
        code: c.textPrimary,
        heading: c.accentPrimary,
        h1: '#569CD6',
        h2: '#4EC9B0',
        h3: '#DCDCAA',
        h4: '#9CDCFE',
        h5: '#CE9178',
        h6: c.textMuted,
        textPrimary: c.textPrimary
      };
    },
    htmlScheme: getHtmlColorScheme('dark','dark')
  },
  {
    id: 'xela-arctic-glass',
    name: 'XELA Arctic Glass — Crystal Light',
    type: 'light',
    roles: {
      surface0: '#FFFFFF',
      surface1: '#F7FBFE',
      surface2: '#F2F8FC',
      surface3: '#ECF7FD',
      panel: '#F7FBFE',
      overlay: '#FFFFFFCC',
      backdrop: '#FFFFFF88',
      border: '#E2E8F0',
      focus: withAlpha('#06B6D4',0.67),
      textPrimary: '#0F172A',
      textSecondary: '#334155',
      textMuted: '#64748B',
      textInverted: '#FFFFFF',
      accentPrimary: '#06B6D4',
      accentPrimaryAlt: '#22D3EE',
      accentInfo: '#0EA5E9',
      accentWarn: '#EAB308',
      accentError: '#EF4444',
      accentSuccess: '#10B981',
      accentSelection: withAlpha('#06B6D4',0.13),
      accentLink: '#06B6D4'
    },
    tokens(c){
      return {
        comment: '#64748B',
        keyword: '#0EA5E9',
        function: '#06B6D4',
        variable: '#475569',
        string: '#10B981',
        number: '#EAB308',
        constant: '#8B5CF6',
        storage: '#EC4899',
        type: '#3B82F6',
        punctuation: c.textPrimary,
        invalid: '#EF4444',
        code: c.textPrimary,
        heading: c.accentPrimary,
        h1: '#0F172A',
        h2: '#06B6D4',
        h3: '#0EA5E9',
        h4: '#60A5FA',
        h5: '#10B981',
        h6: c.textMuted,
        textPrimary: c.textPrimary
      };
    },
    htmlScheme: getHtmlColorScheme('arctic','light')
  },
  {
    id: 'xela-amoled-plus',
    name: 'XELA AMOLED+ — Pure Black Max',
    type: 'dark',
    roles: archetype('black'), // Reuse black archetype
    tokens(c){
      return {
        comment: '#7C7C7C',
        keyword: '#FFD700',
        function: '#00FF00',
        variable: '#FFFFFF',
        string: '#98FB98',
        number: '#FFD700',
        constant: '#FFA500',
        storage: '#FF69B4',
        type: '#87CEEB',
        punctuation: c.textPrimary,
        invalid: '#FF6347',
        code: c.textPrimary,
        heading: c.accentPrimary,
        h1: '#FFD700',
        h2: '#00FF00',
        h3: '#FF69B4',
        h4: '#87CEEB',
        h5: '#98FB98',
        h6: c.textMuted,
        textPrimary: c.textPrimary
      };
    },
    htmlScheme: getHtmlColorScheme('amoled','dark')
  },
  {
    id: 'xela-graph-paper',
    name: 'XELA Graph Paper — Light Grid',
    type: 'light',
    roles: {
      surface0: '#FEFEFE',
      surface1: '#F9F9F9',
      surface2: '#F0F0F0',
      surface3: '#E8E8E8',
      panel: '#F9F9F9',
      overlay: '#FEFEFEFC',
      backdrop: '#FFFFFF88',
      border: '#E0E0E0',
      focus: withAlpha('#1976D2',0.67),
      textPrimary: '#212121',
      textSecondary: '#424242',
      textMuted: '#757575',
      textInverted: '#FFFFFF',
      accentPrimary: '#1976D2',
      accentPrimaryAlt: '#2196F3',
      accentInfo: '#0288D1',
      accentWarn: '#F57C00',
      accentError: '#D32F2F',
      accentSuccess: '#388E3C',
      accentSelection: withAlpha('#1976D2',0.1),
      accentLink: '#1976D2'
    },
    tokens(c){
      return {
        comment: '#9E9E9E',
        keyword: '#5E35B1',
        function: '#1976D2',
        variable: '#212121',
        string: '#388E3C',
        number: '#F57C00',
        constant: '#7B1FA2',
        storage: '#C2185B',
        type: '#0288D1',
        punctuation: c.textPrimary,
        invalid: '#D32F2F',
        code: c.textPrimary,
        heading: c.accentPrimary,
        h1: '#212121',
        h2: '#1976D2',
        h3: '#5E35B1',
        h4: '#0288D1',
        h5: '#388E3C',
        h6: c.textMuted,
        textPrimary: c.textPrimary
      };
    },
    htmlScheme: getHtmlColorScheme('graph','light')
  },
  {
    id: 'xela-ink',
    name: 'XELA Ink — Print Typography',
    type: 'light',
    roles: {
      surface0: '#FFFEF7',
      surface1: '#FAF9F2',
      surface2: '#F5F4ED',
      surface3: '#F0EFE8',
      panel: '#FAF9F2',
      overlay: '#FFFEF7CC',
      backdrop: '#FFFFFF88',
      border: '#E8E7E0',
      focus: withAlpha('#8B4513',0.67),
      textPrimary: '#2F2F2F',
      textSecondary: '#4A4A4A',
      textMuted: '#6B6B6B',
      textInverted: '#FFFFFF',
      accentPrimary: '#8B4513',
      accentPrimaryAlt: '#A0522D',
      accentInfo: '#4682B4',
      accentWarn: '#DAA520',
      accentError: '#B22222',
      accentSuccess: '#228B22',
      accentSelection: withAlpha('#8B4513',0.1),
      accentLink: '#4682B4'
    },
    tokens(c){
      return {
        comment: '#708090',
        keyword: '#8B008B',
        function: '#8B4513',
        variable: '#2F2F2F',
        string: '#228B22',
        number: '#DAA520',
        constant: '#8B008B',
        storage: '#B22222',
        type: '#4682B4',
        punctuation: c.textPrimary,
        invalid: '#B22222',
        code: c.textPrimary,
        heading: c.accentPrimary,
        h1: '#2F2F2F',
        h2: '#8B4513',
        h3: '#8B008B',
        h4: '#4682B4',
        h5: '#228B22',
        h6: c.textMuted,
        textPrimary: c.textPrimary
      };
    },
    htmlScheme: getHtmlColorScheme('ink','light')
  },
  {
    id: 'xela-terminalist',
    name: 'XELA Terminalist — ANSI Native',
    type: 'dark',
    roles: {
      surface0: '#0B0D10',
      surface1: '#0F1216',
      surface2: '#1F242B',
      surface3: '#374151',
      panel: '#0F1216',
      overlay: '#0B0D10CC',
      backdrop: '#00000088',
      border: '#1F242B',
      focus: withAlpha('#3B82F6',0.67),
      textPrimary: '#E5E7EB',
      textSecondary: '#D1D5DB',
      textMuted: '#9CA3AF',
      textInverted: '#111827',
      accentPrimary: '#3B82F6',
      accentPrimaryAlt: '#60A5FA',
      accentInfo: '#06B6D4',
      accentWarn: '#F59E0B',
      accentError: '#EF4444',
      accentSuccess: '#22C55E',
      accentSelection: withAlpha('#93C5FD',0.13),
      accentLink: '#22D3EE'
    },
    tokens(c){
      return {
        comment: '#6B7280',
        keyword: '#A855F7',
        function: '#06B6D4',
        variable: '#E5E7EB',
        string: '#22C55E',
        number: '#F59E0B',
        constant: '#C084FC',
        storage: '#EF4444',
        type: '#60A5FA',
        punctuation: c.textPrimary,
        invalid: '#F87171',
        code: c.textPrimary,
        heading: c.accentPrimary,
        h1: '#FFFFFF',
        h2: '#60A5FA',
        h3: '#C084FC',
        h4: '#22D3EE',
        h5: '#4ADE80',
        h6: c.textMuted,
        textPrimary: c.textPrimary
      };
    },
    htmlScheme: getHtmlColorScheme('terminalist','dark')
  },
  {
    id: 'xela-e-ink-sepia',
    name: 'XELA E‑Ink Sepia — Paper Light',
    type: 'light',
    roles: {
      surface0: '#FBF7F0',
      surface1: '#F6F2EB',
      surface2: '#F1EDE6',
      surface3: '#ECE8E1',
      panel: '#F6F2EB',
      overlay: '#FBF7F0CC',
      backdrop: '#FFFFFF88',
      border: '#E0DCD5',
      focus: withAlpha('#8B4513',0.67),
      textPrimary: '#3C2415',
      textSecondary: '#4A2F1B',
      textMuted: '#6B4E37',
      textInverted: '#FBF7F0',
      accentPrimary: '#8B4513',
      accentPrimaryAlt: '#A0522D',
      accentInfo: '#5D4E37',
      accentWarn: '#D2691E',
      accentError: '#A0522D',
      accentSuccess: '#556B2F',
      accentSelection: withAlpha('#8B4513',0.1),
      accentLink: '#5D4E37'
    },
    tokens(c){
      return {
        comment: '#8B7355',
        keyword: '#8B4513',
        function: '#5D4E37',
        variable: '#3C2415',
        string: '#556B2F',
        number: '#D2691E',
        constant: '#8B4513',
        storage: '#A0522D',
        type: '#5D4E37',
        punctuation: c.textPrimary,
        invalid: '#A0522D',
        code: c.textPrimary,
        heading: c.accentPrimary,
        h1: '#3C2415',
        h2: '#8B4513',
        h3: '#5D4E37',
        h4: '#6B4E37',
        h5: '#556B2F',
        h6: c.textMuted,
        textPrimary: c.textPrimary
      };
    },
    htmlScheme: getHtmlColorScheme('sepia','light')
  },
  ...additionalThemes,
  ...finalThemes
];
