/**
 * Theme: XELA Barbie — Dreamhouse Pink
 * Type: light
 * Auto-generated from popculture collection
 */

import { getHtmlColorScheme } from '../html-tokens.js';
import { withAlpha } from '../roles.js';

export default {
  id: 'xela-barbie',
  name: 'XELA Barbie — Dreamhouse Pink',
  type: 'light',
  roles: {
      "surface0": "#FFF0F5",
      "surface1": "#FFE5F0",
      "surface2": "#FFD6E8",
      "surface3": "#FFC2DD",
      "panel": "#FFFFFF",
      "overlay": "#FFF0F5FF",
      "backdrop": "#FFE5F099",
      "border": "#FFC2DD",
      "focus": "#E91E6399",
      "textPrimary": "#1A1A1A",
      "textSecondary": "#4A4A4A",
      "textMuted": "#8A8A8A",
      "textInverted": "#FFFFFF",
      "accentPrimary": "#E91E63",
      "accentPrimaryAlt": "#FF4081",
      "accentInfo": "#BA68C8",
      "accentWarn": "#FF6F00",
      "accentError": "#D32F2F",
      "accentSuccess": "#00C853",
      "accentSelection": "#E91E632E",
      "accentLink": "#E91E63"
  },
  colorOverrides: {
      "editor.background": "#FFF0F5",
      "editor.foreground": "#1A1A1A",
      "titleBar.activeBackground": "#FFE5F0",
      "titleBar.activeForeground": "#4A4A4A",
      "titleBar.border": "#FFC2DD",
      "activityBar.background": "#FFE5F0",
      "activityBar.foreground": "#4A4A4A",
      "activityBar.inactiveForeground": "#8A8A8A",
      "activityBar.border": "#FFC2DD",
      "activityBar.activeBorder": "#E91E63",
      "activityBarBadge.background": "#E91E63",
      "activityBarBadge.foreground": "#FFFFFF",
      "sideBar.background": "#FFE5F0",
      "sideBar.foreground": "#4A4A4A",
      "sideBar.border": "#FFC2DD",
      "sideBarTitle.foreground": "#1A1A1A",
      "sideBarSectionHeader.background": "#FFD6E8",
      "sideBarSectionHeader.foreground": "#E91E63",
      "editorGroupHeader.tabsBackground": "#FFE5F0",
      "editorGroupHeader.border": "#FFC2DD",
      "tab.activeBackground": "#FFF0F5",
      "tab.activeForeground": "#1A1A1A",
      "tab.inactiveBackground": "#FFE5F0",
      "tab.inactiveForeground": "#8A8A8A",
      "tab.border": "#FFC2DD",
      "tab.activeBorder": "#00000000",
      "tab.activeBorderTop": "#E91E63",
      "statusBar.background": "#E91E63",
      "statusBar.foreground": "#FFFFFF",
      "statusBar.border": "#00000000",
      "statusBar.debuggingBackground": "#FF4081",
      "statusBar.debuggingForeground": "#FFFFFF",
      "panel.background": "#FFFFFF",
      "panel.border": "#FFC2DD",
      "panelTitle.activeBorder": "#E91E63",
      "panelTitle.activeForeground": "#1A1A1A",
      "panelTitle.inactiveForeground": "#8A8A8A",
      "terminal.background": "#FFFFFF",
      "terminal.foreground": "#4A4A4A",
      "terminalCursor.foreground": "#E91E63",
      "editorLineNumber.foreground": "#FFC2DD",
      "editorLineNumber.activeForeground": "#8A8A8A",
      "editor.lineHighlightBackground": "#FFD6E8B0",
      "editorCursor.foreground": "#E91E63",
      "editorWhitespace.foreground": "#FFC2DD60",
      "editorIndentGuide.background1": "#FFC2DD50",
      "editorIndentGuide.activeBackground1": "#E91E6360",
      "editorRuler.foreground": "#FFC2DD",
      "editorBracketMatch.background": "#E91E6328",
      "editorBracketMatch.border": "#E91E6390",
      "editor.selectionBackground": "#E91E6330",
      "editor.selectionHighlightBackground": "#E91E6320",
      "editor.inactiveSelectionBackground": "#E91E6318",
      "editor.wordHighlightBackground": "#BA68C828",
      "editor.wordHighlightStrongBackground": "#BA68C838",
      "editor.findMatchBackground": "#FF6F0050",
      "editor.findMatchHighlightBackground": "#FF6F0028",
      "list.activeSelectionBackground": "#FFD6E8",
      "list.activeSelectionForeground": "#1A1A1A",
      "list.inactiveSelectionBackground": "#FFE5F0",
      "list.hoverBackground": "#FFD6E8C0",
      "list.focusBackground": "#FFC2DD",
      "list.highlightForeground": "#E91E63",
      "input.background": "#FFFFFF",
      "input.border": "#FFC2DD",
      "input.foreground": "#1A1A1A",
      "input.placeholderForeground": "#8A8A8A",
      "dropdown.background": "#FFFFFF",
      "dropdown.border": "#FFC2DD",
      "dropdown.foreground": "#1A1A1A",
      "button.background": "#E91E63",
      "button.foreground": "#FFFFFF",
      "button.hoverBackground": "#FF4081",
      "badge.background": "#E91E63",
      "badge.foreground": "#FFFFFF",
      "minimap.background": "#FFF0F5",
      "minimap.findMatchHighlight": "#FF6F0060",
      "minimap.selectionHighlight": "#E91E6350",
      "breadcrumb.background": "#FFE5F0",
      "breadcrumb.foreground": "#8A8A8A",
      "breadcrumb.focusForeground": "#1A1A1A",
      "breadcrumb.activeSelectionForeground": "#E91E63",
      "scrollbarSlider.background": "#8A8A8A30",
      "scrollbarSlider.hoverBackground": "#8A8A8A50",
      "scrollbarSlider.activeBackground": "#8A8A8A70",
      "gitDecoration.addedResourceForeground": "#00C853",
      "gitDecoration.modifiedResourceForeground": "#BA68C8",
      "gitDecoration.deletedResourceForeground": "#D32F2F",
      "gitDecoration.untrackedResourceForeground": "#FF4081",
      "gitDecoration.ignoredResourceForeground": "#BDBDBD"
  },
  tokens: function(c){
      return {
        comment: '#BDBDBD',
        keyword: '#E91E63',
        function: '#BA68C8',
        variable: '#4A4A4A',
        string: '#00C853',
        number: '#FF6F00',
        constant: '#FF4081',
        storage: '#E91E63',
        type: '#BA68C8',
        punctuation: c.textPrimary,
        invalid: '#D32F2F',
        code: c.textPrimary,
        heading: c.accentPrimary,
        h1: '#E91E63',
        h2: '#FF4081',
        h3: '#BA68C8',
        h4: '#FF6F00',
        h5: '#00C853',
        h6: c.textMuted,
        textPrimary: c.textPrimary
      };
    },
  htmlScheme: {"htmlTag":"#F7B883","htmlStructureTag":"#FFD166","htmlInlineTag":"#EADCB2","htmlScriptTag":"#FF3CAC","htmlAttribute":"#EADCB2","htmlClassAttribute":"#C8B0FF","htmlIdAttribute":"#4CFFCA","htmlStyleAttribute":"#FF8BDA","htmlEventAttribute":"#D8C8FF","htmlAttributeValue":"#00F5A0","htmlAttributeValueString":"#98FF66","htmlTagBrackets":"#A6AAB4","htmlPunctuation":"#8E93A6","htmlStringPunctuation":"#9AA0B4","htmlComment":"#8E93A6","htmlEntity":"#F2C97D","htmlEntityPunctuation":"#FFD166","htmlDoctype":"#FF3CAC","embeddedCss":"#E0CCFF","embeddedCssBlock":"#D7C7FF","embeddedJs":"#F7B883","embeddedJsBlock":"#EADCB2","htmlFormTag":"#79E49A","htmlFormAttribute":"#98FF66","htmlTableTag":"#4CFFCA","htmlMediaTag":"#FFD166","htmlLinkTag":"#4CFFCA","htmlHrefAttribute":"#00F5A0","htmlSemanticTag":"#C8B0FF","htmlText":"#F7F8FA"}
};
