/**
 * Theme: XELA Netflix — Streaming Cinema
 * Type: dark
 * Auto-generated from popculture collection
 */

import { getHtmlColorScheme } from '../html-tokens.js';
import { withAlpha } from '../roles.js';

export default {
  id: 'xela-netflix',
  name: 'XELA Netflix — Streaming Cinema',
  type: 'dark',
  roles: {
      "surface0": "#141414",
      "surface1": "#181818",
      "surface2": "#1F1F1F",
      "surface3": "#2A2A2A",
      "panel": "#181818",
      "overlay": "#141414F8",
      "backdrop": "#00000099",
      "border": "#2A2A2A",
      "focus": "#E5091499",
      "textPrimary": "#FFFFFF",
      "textSecondary": "#E5E5E5",
      "textMuted": "#B3B3B3",
      "textInverted": "#141414",
      "accentPrimary": "#E50914",
      "accentPrimaryAlt": "#F40612",
      "accentInfo": "#46D369",
      "accentWarn": "#F89F1C",
      "accentError": "#E50914",
      "accentSuccess": "#46D369",
      "accentSelection": "#E5091440",
      "accentLink": "#5799EF"
  },
  colorOverrides: {
      "editor.background": "#141414",
      "editor.foreground": "#FFFFFF",
      "titleBar.activeBackground": "#141414",
      "titleBar.activeForeground": "#FFFFFF",
      "titleBar.border": "#00000000",
      "activityBar.background": "#181818",
      "activityBar.foreground": "#E5E5E5",
      "activityBar.inactiveForeground": "#B3B3B3",
      "activityBar.border": "#00000000",
      "activityBar.activeBorder": "#E50914",
      "activityBarBadge.background": "#E50914",
      "activityBarBadge.foreground": "#FFFFFF",
      "sideBar.background": "#181818",
      "sideBar.foreground": "#E5E5E5",
      "sideBar.border": "#2A2A2A80",
      "sideBarTitle.foreground": "#FFFFFF",
      "sideBarSectionHeader.background": "#1F1F1F",
      "sideBarSectionHeader.foreground": "#FFFFFF",
      "editorGroupHeader.tabsBackground": "#181818",
      "editorGroupHeader.border": "#2A2A2A",
      "tab.activeBackground": "#141414",
      "tab.activeForeground": "#FFFFFF",
      "tab.inactiveBackground": "#181818",
      "tab.inactiveForeground": "#B3B3B3",
      "tab.border": "#00000000",
      "tab.activeBorder": "#00000000",
      "tab.activeBorderTop": "#E50914",
      "tab.hoverBackground": "#1F1F1F",
      "statusBar.background": "#E50914",
      "statusBar.foreground": "#FFFFFF",
      "statusBar.border": "#00000000",
      "statusBar.debuggingBackground": "#46D369",
      "statusBar.debuggingForeground": "#141414",
      "panel.background": "#181818",
      "panel.border": "#2A2A2A",
      "panelTitle.activeBorder": "#E50914",
      "panelTitle.activeForeground": "#FFFFFF",
      "panelTitle.inactiveForeground": "#B3B3B3",
      "terminal.background": "#181818",
      "terminal.foreground": "#E5E5E5",
      "terminalCursor.foreground": "#E50914",
      "editorLineNumber.foreground": "#2A2A2A",
      "editorLineNumber.activeForeground": "#B3B3B3",
      "editor.lineHighlightBackground": "#1F1F1F80",
      "editorCursor.foreground": "#E50914",
      "editorWhitespace.foreground": "#2A2A2A50",
      "editorIndentGuide.background1": "#2A2A2A40",
      "editorIndentGuide.activeBackground1": "#E5091460",
      "editorRuler.foreground": "#2A2A2A",
      "editorBracketMatch.background": "#E5091430",
      "editorBracketMatch.border": "#E5091490",
      "editor.selectionBackground": "#E5091438",
      "editor.selectionHighlightBackground": "#E5091420",
      "editor.inactiveSelectionBackground": "#E5091418",
      "editor.wordHighlightBackground": "#5799EF28",
      "editor.wordHighlightStrongBackground": "#5799EF38",
      "editor.findMatchBackground": "#F89F1C60",
      "editor.findMatchHighlightBackground": "#F89F1C30",
      "list.activeSelectionBackground": "#1F1F1F",
      "list.activeSelectionForeground": "#FFFFFF",
      "list.inactiveSelectionBackground": "#2A2A2A50",
      "list.hoverBackground": "#1F1F1F80",
      "list.focusBackground": "#2A2A2A",
      "list.highlightForeground": "#E50914",
      "input.background": "#1F1F1F",
      "input.border": "#2A2A2A",
      "input.foreground": "#FFFFFF",
      "input.placeholderForeground": "#B3B3B3",
      "dropdown.background": "#1F1F1F",
      "dropdown.border": "#2A2A2A",
      "dropdown.foreground": "#FFFFFF",
      "button.background": "#E50914",
      "button.foreground": "#FFFFFF",
      "button.hoverBackground": "#F40612",
      "badge.background": "#E50914",
      "badge.foreground": "#FFFFFF",
      "minimap.background": "#141414",
      "minimap.findMatchHighlight": "#F89F1C70",
      "minimap.selectionHighlight": "#E5091460",
      "breadcrumb.background": "#181818",
      "breadcrumb.foreground": "#B3B3B3",
      "breadcrumb.focusForeground": "#FFFFFF",
      "breadcrumb.activeSelectionForeground": "#E50914",
      "scrollbarSlider.background": "#B3B3B330",
      "scrollbarSlider.hoverBackground": "#B3B3B350",
      "scrollbarSlider.activeBackground": "#B3B3B370",
      "gitDecoration.addedResourceForeground": "#46D369",
      "gitDecoration.modifiedResourceForeground": "#5799EF",
      "gitDecoration.deletedResourceForeground": "#E50914",
      "gitDecoration.untrackedResourceForeground": "#F89F1C",
      "gitDecoration.ignoredResourceForeground": "#808080"
  },
  tokens: function(c){
      return {
        comment: '#808080',
        keyword: '#E50914',
        function: '#5799EF',
        variable: '#E5E5E5',
        string: '#46D369',
        number: '#F89F1C',
        constant: '#F40612',
        storage: '#E50914',
        type: '#5799EF',
        punctuation: c.textPrimary,
        invalid: '#E50914',
        code: c.textPrimary,
        heading: c.accentPrimary,
        h1: '#E50914',
        h2: '#5799EF',
        h3: '#46D369',
        h4: '#F89F1C',
        h5: '#E5E5E5',
        h6: c.textMuted,
        textPrimary: c.textPrimary
      };
    },
  htmlScheme: {"htmlTag":"#F7B883","htmlStructureTag":"#FFD166","htmlInlineTag":"#EADCB2","htmlScriptTag":"#FF3CAC","htmlAttribute":"#EADCB2","htmlClassAttribute":"#C8B0FF","htmlIdAttribute":"#4CFFCA","htmlStyleAttribute":"#FF8BDA","htmlEventAttribute":"#D8C8FF","htmlAttributeValue":"#00F5A0","htmlAttributeValueString":"#98FF66","htmlTagBrackets":"#A6AAB4","htmlPunctuation":"#8E93A6","htmlStringPunctuation":"#9AA0B4","htmlComment":"#8E93A6","htmlEntity":"#F2C97D","htmlEntityPunctuation":"#FFD166","htmlDoctype":"#FF3CAC","embeddedCss":"#E0CCFF","embeddedCssBlock":"#D7C7FF","embeddedJs":"#F7B883","embeddedJsBlock":"#EADCB2","htmlFormTag":"#79E49A","htmlFormAttribute":"#98FF66","htmlTableTag":"#4CFFCA","htmlMediaTag":"#FFD166","htmlLinkTag":"#4CFFCA","htmlHrefAttribute":"#00F5A0","htmlSemanticTag":"#C8B0FF","htmlText":"#F7F8FA"}
};
